version: '3.9'
services:
  oereb-db:
    image: ghcr.io/edigonzales/oereb-database:2
    environment:
      POSTGRESQL_DATABASE: oereb
      POSTGRESQL_POSTGRES_PASSWORD: postgres
      POSTGRESQL_USERNAME: ddluser
      POSTGRESQL_PASSWORD: ddluser
    ports:
      - "54323:5432"
    volumes:
      - pgdata_oereb:/bitnami/postgresql:cached

volumes:
  pgdata_oereb:

